version: 0.2
env:
  secrets-manager:
    aws_access_id: AWS_SECRET:AWS_SECRET_ID
    aws_access_key: AWS_SECRET:AWS_SECRET_KEY
phases:
  install:
    commands:
      - echo install serverless framework
      - npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
      - npm install
  build:
    commands:
      - echo deployment started `date`
      - serverless config credentials --provider aws --key $aws_access_id --secret $aws_access_key
      - serverless deploy --stage dev --region ap-southeast-1
  post_build:
    commands:
      - echo post build completed on `date`