service: my-express-application
custom:
  xyzsecret: ${ssm:/aws/reference/secretsmanager/testsecrect}
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  tracing:
    lambda: true
  environment:
    accessKeyId: ${self:custom.xyzsecret.user}
    secretAccessKey: ${self:custom.xyzsecret.password}
    db_username: ${ssm:/path/to/service/parameterStore}
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'               