service: my-express-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  custom:
    supersecret: ${ssm:/aws/reference/secretsmanager/AWS_SECRET/AWS_SECRET_ID~true}
  tracing:
    lambda: true
  environment:
    APP_DOMAIN: ${ssm:parameterStore}
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'               