service: my-express-application
custom:
  xyzsecret: ${ssm:/aws/reference/secretsmanager/testsecrect}
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  tracing:
    lambda: true
  environment:
    accessKeyId: ${self:custom.xyzsecret.user}
    secretAccessKey: ${self:custom.xyzsecret.password}
    db_username: ${ssm:db_username}
    db_password: ${ssm:db_password}
  vpc:
    securityGroupIds:
      - sg-0d190b7e8a1a0cc67
    subnetdIds:
      - subnet-01284e1476120c5c9
      - subnet-030b666c5e41cb1ca
      - subnet-030b666c5e41cb1ca 
functions:
  app:
    handler: index.handler
    vpc:
      securityGroupIds:
        - sg-0d190b7e8a1a0cc67
      subnetIds:
        - subnet-01284e1476120c5c9
        - subnet-030b666c5e41cb1ca
        - subnet-030b666c5e41cb1ca 
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'               